service: thelitas-admin

custom:
  s3BucketSuffix: webroot
  s3BucketName: ${self:service}-${self:provider.stage}-${self:custom.s3BucketSuffix}
  fullstack:
    domain: 
      - "admin.thelitas.co"
    certificate: "	arn:aws:acm:us-east-1:315118507072:certificate/416d5b45-4454-4385-9f3e-480dd42097b7"
    bucketName: ${self:custom.s3BucketSuffix}
    clientCommand: yarn build          
    distributionFolder: build            
    indexDocument: index.html 
    singlePageApp: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  memorySize: 1024 # default is 1024
  timeout: 30 # max for API Gateway

plugins:
  - fullstack-serverless
